const state={screen:1,waybill:'',total:0,scanned:0,drugTarget:5,drugScanned:0,blocked:false};
const audio=new(window.AudioContext||window.webkitAudioContext)();
function play(t){const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);if(t==='ok'){o.frequency.value=1200;g.gain.value=0.3;o.start();setTimeout(()=>o.stop(),100)}else if(t==='err'){o.frequency.value=300;g.gain.value=0.5;o.start();setTimeout(()=>o.stop(),500)}else{o.frequency.value=1500;g.gain.value=0.3;o.start();setTimeout(()=>o.stop(),300)}}
function toast(m,t=''){const e=document.getElementById('toast');e.textContent=m;e.className='toast '+t;e.style.display='block';setTimeout(()=>e.style.display='none',2000)}
function switchScreen(n){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.querySelectorAll('.dot').forEach((d,i)=>d.classList.toggle('active',i+1===n));document.getElementById('s'+n).classList.add('active');state.screen=n}
function startWave(){const v=document.getElementById('waveInput').value.trim();if(!v){toast('请输入波次号','warning');return}if(state.blocked){document.getElementById('blockModal').classList.add('active');play('err');return}state.waybill='SF'+Math.floor(Math.random()*1e9);state.total=Math.floor(Math.random()*10)+5;state.scanned=0;update();switchScreen(2);toast('任务加载成功','success');play('ok')}
function update(){document.getElementById('waybill').textContent=state.waybill;document.getElementById('scanCount').textContent=state.scanned+'/'+state.total;const p=(state.scanned/state.total)*100;document.getElementById('progressFill').style.width=p+'%';document.getElementById('progressText').textContent='波次进度：'+state.scanned+'/'+state.total+' 单'}
function simNormal(){if(state.screen!==2){toast('请先切换到扫描页','warning');return}document.getElementById('barcode').textContent='6901234567890';document.getElementById('productName').textContent='阿莫西林胶囊 0.25g*24 粒';document.getElementById('scanPrompt').textContent='商品条码已扫描';play('ok');setTimeout(()=>{state.drugScanned=0;updateDrug();document.getElementById('drugModal').classList.add('active')},500)}
function closeDrug(){document.getElementById('drugModal').classList.remove('active');document.getElementById('scanPrompt').textContent='请扫描商品条码';document.getElementById('barcode').textContent='-';document.getElementById('drugInput').value='';document.getElementById('drugInput').classList.remove('error','success')}
function confirmDrug(){const c=document.getElementById('drugInput').value.trim();if(!c.match(/^8\d{19}$/)){document.getElementById('drugInput').classList.add('error');toast('药监码格式错误（8 开头 20 位）','error');play('err');return}document.getElementById('drugInput').classList.remove('error');document.getElementById('drugInput').classList.add('success');state.drugScanned++;updateDrug();play('ok');if(state.drugScanned>=state.drugTarget){setTimeout(()=>{closeDrug();state.scanned++;update();toast('本单完成','success');play('ok')},800)}}
function updateDrug(){document.getElementById('drugCount').textContent=state.drugScanned;const p=(state.drugScanned/state.drugTarget)*100;document.getElementById('drugProgress').style.width=p+'%';document.getElementById('drugTarget').textContent='目标：'+state.drugScanned+'/'+state.drugTarget}
function simTwoInOne(){if(state.screen!==2){toast('请先切换到扫描页','warning');return}document.getElementById('barcode').textContent='81234567890123456789';document.getElementById('productName').textContent='布洛芬缓释胶囊 (二码合一)';toast('检测到二码合一商品','success');play('ok');setTimeout(()=>{state.scanned++;update();document.getElementById('scanPrompt').textContent='请扫描商品条码';document.getElementById('barcode').textContent='-';toast('二码合一自动录入成功','success');play('ok')},800)}
function simComplete(){document.getElementById('waybill').textContent='-';document.getElementById('scanCount').textContent='0/0';document.getElementById('productName').textContent='等待扫描...';document.getElementById('barcode').textContent='-';document.getElementById('scanPrompt').textContent='请扫描商品条码';state.waybill='SF'+Math.floor(Math.random()*1e9);state.total=Math.floor(Math.random()*10)+5;state.scanned=0;setTimeout(()=>{update();toast('本单完成，已切换下一单','success');play('ok')},500)}
function simWaveSwitch(){state.blocked=true;document.getElementById('blockText').textContent='当前波次 [20231027-01] 尚有 [12] 单未扫描，禁止切换波次。';document.getElementById('blockModal').classList.add('active');play('err')}
function showPwd(){document.getElementById('pwdModal').classList.add('active');document.getElementById('pwdInput').value=''}
function closePwd(){document.getElementById('pwdModal').classList.remove('active')}
function verifyPwd(){if(document.getElementById('pwdInput').value==='123456'){toast('验证成功，已跳过','success');closePwd();play('ok')}else{toast('密码错误','error');play('err')}}
document.getElementById('waveInput').addEventListener('keypress',e=>{if(e.key==='Enter')startWave()});
document.getElementById('drugInput').addEventListener('keypress',e=>{if(e.key==='Enter')confirmDrug()});
document.getElementById('pwdInput').addEventListener('keypress',e=>{if(e.key==='Enter')verifyPwd()});
